server:
  port: 80
spring:
  application:
    name: cloud-eureka-client-consumer-feign
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.232.201:3306/user
    username: root
    password: xiwen123
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    # 更倾向使用ip地址，而不是host名：鼠标移上去，显示ip
    prefer-ip-address: true
    #设置成当前客户端ip,显示的时候直接显示ip
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#针对的被调用方微服务名称,不加就是全局⽣效
CLOUD-EUREKA-CLIENT-PROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #负载策略调整

#设置Feign客户端超时时间（openfeign默认支持ribbon）
ribbon:
  ConnectTimeout: 5000 #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所用的时间

#配置Feign客户端日志
logging:
  level:
    com.xiwen.cloud.feign.MovieFeignClient: debug
