server:
  port: 8007
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.11.162:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    root: info
  file:
    path: doing-cron
