server:
  port: 8200

spring:
  cloud:
    gateway:
      routes:
        - id: service-system
          uri: lb://service-system
          predicates:
            - Path=/*/system/**
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-yun
          uri: lb://service-yun
          predicates:
            - Path=/*/yun/**