server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: service-system
          uri: lb://service-system
          predicates:
            - Path=/*/system/**
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**
        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/cmn/**
