server:
  port: 8082

spring:
  xxxx:
    jdbc:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.dirver
        url: jdbc:mysql://localhost:3306/springboot02
        username: root
        password: root
        hobbys:
          - hhh
          - nihao
          - 测试