server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33068/guigu-auth
    username: root
    password: xiwen123

#打印日志1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 一般不设置
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      logic-delete-field: isDeleted #全局指定实体类中哪个字段逻辑删除 ，使用注解的就是局部的

#打印日志2
#logging:
#  level:
#    #   代表所有依赖的包都是info级别
#    # root: debug
#    # 指定某个包下的使用某个级别的日志
#    com.xiwen.system.mapper: debug

