server:
  port: 8080
spring:
  application:
    name: demo-api
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:  classpath:/mapper/**/*.xml

# swagger
netrain:
  swagger:
    title: 初始接口文档标题
