server:
  port: 8001
spring:
  application:
    name: cloud-eureka-client-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.232.201:3306/test
    username: root
    password: xiwen123
  zipkin:
    #指定数据提交到的zipkin服务端接收
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于0~1之间，1表示全部采样
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    # 更倾向使用ip地址，而不是host名：鼠标移上去，显示ip
    prefer-ip-address: true
    #设置成当前客户端ip,显示的时候直接显示ip
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


