spring:
  #测试数据源
  aaa:
    jdbc:
      datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:///springboot_01
        username: root
        password: root
        type: c3p0
  #测试激活文件
  profiles:
    active: dev
server:
  servlet:
    #设置项目上下文路径
    context-path: /demo04

