server:
  port: 8002

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: xiwen123
    url: jdbc:mysql://124.221.11.162:3306/guigu_syt_hosp?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  cloud:
    nacos:
      server-addr: 124.221.11.162:8848

  application:
    name: service-hosp
  data:
    mongodb:
      host: 124.221.11.162
      port: 27017
      username: syt
      password: syt123
      database: syt

logging:
  level:
    root: info
  #    com.atguigu.syt.hosp.controller.admin: info
    org:
      mongodb:
        driver:
          protocol:
            command: debug
  file:
    path: hosp
