spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33068/springboot?serverTimezone=Asia/Shanghai
    username: root
    password: xiwen123
  #redis
  redis:
    host: 192.168.232.201
    port: 6379
    password: redis123
  #指定admin-server服务端的注册地址
  boot:
    admin:
      client:
        url: http://localhost:8888
  application:
    name: admin-client
#健康监控 如果不设置base-path路径默认上下文路径是 actuator
management:
  endpoints:
    web:
      exposure:
        #可以去官网查看开放的端口，如果要开放所有端口需要设置为（必须要带引号要不可能会报错）： '*' 或者指定某些端口 health,info
        include: '*'
      base-path: /a # 默认是actuator
  server:
    port: 9999
  endpoint:
    health:
      show-details: always # 显示所有健康状态


