mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/xml/*.xml

server:
  port: 8006
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 124.221.11.162:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: xiwen123
    url: jdbc:mysql://124.221.11.162:3306/guigu_syt_order?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    root: info
  file:
    path: order

feign:
  sentinel:
    enabled: true #开启Feign对Sentinel的支持
  client:
    config:
      default:
        connect-timeout: 4000 #连接建立的超时时长，单位是ms，默认1s
        read-timeout: 4000 #处理请求的超时时间，单位是ms，默认为1s