# 服务端口
server:
  port: 8301
  # 服务名
spring:
  application:
    name: service-vod
  
  # 环境设置：dev、test、prod
  profiles:
    active: dev

    # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33068/glkt_vod?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xiwen123
  
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  
  #mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl