package com.xiwen.mbg2.bean;

public class Departments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.id
     *
     * @mbg.generated Thu Apr 06 17:57:12 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.name
     *
     * @mbg.generated Thu Apr 06 17:57:12 CST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.id
     *
     * @return the value of departments.id
     *
     * @mbg.generated Thu Apr 06 17:57:12 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.id
     *
     * @param id the value for departments.id
     *
     * @mbg.generated Thu Apr 06 17:57:12 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.name
     *
     * @return the value of departments.name
     *
     * @mbg.generated Thu Apr 06 17:57:12 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.name
     *
     * @param name the value for departments.name
     *
     * @mbg.generated Thu Apr 06 17:57:12 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }
}